part of 'skills.dart';

List<String> _mySkills = [
  'Flutter',
  'Dart',
  'Firebase Firestore/Auth',
  'Firebase Functions',
  'FCM',
  'Firebase Analytics/Crashlytics',
  'Firebase Storage',
  'Firebase Realtime DB',
  'Google Maps Integration',
  'sqflite',
  'Hive',
  'Shared preferences',
  'Drift',
  'Secure Storage',
  'Bloc',
  'Cubit',
  'Provider',
  'GetX',
  'GetIt',
  'MVC',
  'MVVM',
  'Injectable',
  'Rest API',
  'WebSockets',
  'GraphQL',
  'Localizations',
  'Google Play publishing',
  'App Store publishing',
  'CI/CD',
  'Exporting data to PDF/Excel/CSV',
  'Local Notifications',
  'Audio',
  'Video',
  'Photo',
  'more...',
];
