part of 'skills.dart';

List<String> _mySkills = [
  'Flutter',
  'Dart',
  'Firebase',
  'Google Map Integration',
  'sqflite',
  'Hive',
  'Shared preferences',
  'Bloc',
  'Cubit',
  'Provider',
  'GetX',
  'GetIt',
  'MVC',
  'MVVM',
  'Injectable',
  'Rest API',
  'WebSockets',
  'GraphQL',
  'Localizations',
  'Google Play publishing',
  'App Store publishing',
  'Exporting to PDF/Excel/CSV',
  'Local Notifications',
  'Audio',
  'Video',
  'Photo',
  'more...',
];
