name: Deploy Web to GitHub

on:
  pull_request:
    branches: [main]

jobs:
  build_number:
    runs-on: ubuntu-latest
    outputs:
      buildnumber: ${{ steps.buildnumber.outputs.build_number }}
    steps:
      - name: Generate Build Number
        id: buildnumber
        uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.GITHUB_TOKEN}}
      - name: Build Number
        run: echo "Build Number - $BUILD_NUMBER"

  publish:
    needs: build_number
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish
        uses: peiffer-innovations/actions-flutter-deploy-pages@v1
        with:
          build_number: ${{ needs.build_number.outputs.buildnumber }}
          deploy_path: web
          repo_url: https://github.com/${{ github.repository }}
          source_path: example
          token: ${{ secrets.GITHUB_TOKEN }}
