name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main # Change if your default branch is different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.0"

      - name: Install dependencies
        run: flutter pub get

      - name: Enable web
        run: flutter config --enable-web

      - name: Build Flutter web
        run: flutter build web --release

      - name: Add CNAME file (custom domain)
        run: |
          cp web/CNAME build/web/CNAME

      - name: Deploy to GitHub Pages
        uses: bluefireteam/flutter-gh-pages@v9
